name: mindscribe_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🎤 Audio + stockage
  record: ^6.2.0
  path_provider: ^2.1.2
  just_audio: ^0.9.40

  # 📄 PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # ⚡ State management
  get: ^4.6.6

  # 🌐 API
  dio: ^5.4.0

  # 💾 Local storage
  shared_preferences: ^2.2.2

  # 🔐 Permissions
  permission_handler: ^11.3.0

  # ✨ Animations
  flutter_animate: ^4.5.0

  # 📊 Graphiques
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21